<?php
$config = array(
	'db'=>array(
			'dbType'=>'mysql',
			'dbHost'=>'172.19.9.13',
			'dbUser'=>'root',
			'dbName'=>'john_db',
			'dbPassword'=>'',
			'dbPort'=>3306,
			),
	'shares'=>array(
			'dbType'=>'mysql',
			'dbHost'=>'172.19.9.13',
			'dbUser'=>'root',
			'dbName'=>'gupiao',
			'dbPassword'=>'',
			'dbPort'=>3306,
			),
	'big_data'=>array(
			'dbType'=>'mysql',
			'dbHost'=>'172.19.9.13',
			'dbUser'=>'root',
			'dbName'=>'big_data',
			'dbPassword'=>'',
			'dbPort'=>3306,
			),
		);

?>